apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        rohatgisanat-amagi/jaja: true
        rohatgisanat-amagi/jenkinsx: true
        rohatgisanat-amagi/p-dev: true
        rohatgisanat-amagi/php-dev: true
        rohatgisanat-amagi/yolo: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        rohatgisanat-amagi/jaja: merge
        rohatgisanat-amagi/jenkinsx: merge
        rohatgisanat-amagi/p-dev: merge
        rohatgisanat-amagi/php-dev: merge
        rohatgisanat-amagi/yolo: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - rohatgisanat-amagi/jenkinsx
        - rohatgisanat-amagi/jaja
        - rohatgisanat-amagi/p-dev
        - rohatgisanat-amagi/php-dev
        - rohatgisanat-amagi/yolo
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - rohatgisanat-amagi/jenkinsx
        - rohatgisanat-amagi/jaja
        - rohatgisanat-amagi/p-dev
        - rohatgisanat-amagi/php-dev
        - rohatgisanat-amagi/yolo
      target_url: http://dashboard-jx.cloudport.amagi.tv
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
