filepath: ""
namespace: jx-production
repositories:
- name: dev
  url: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
releases:
- chart: dev/n-dev
  version: 0.0.13
  name: n-dev
templates: {}
renderedvalues: {}
