filepath: ""
namespace: jx-production
repositories:
- name: dev
  url: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
releases:
- chart: dev/p-dev
  version: 0.0.5
  name: p-dev
templates: {}
renderedvalues: {}
