filepath: ""
namespace: jx-production
repositories:
- name: dev
  url: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
releases:
- chart: dev/yolo
  version: 0.0.1
  name: yolo
templates: {}
renderedvalues: {}
