filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-production
repositories:
- name: dev
  url: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
releases:
- chart: dev/p-dev
  version: 0.0.7
  name: p-dev
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
